language: java

install: mvn install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true

jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7

notifications:
    email:
        - scm@after-sunrise.com
